### ISSUE TITLE
Letsrobot.conf should update to include new options if letsrobot.sample.conf gets updated

### ISSUE THREAD

**Issue by bmorrison4** [letsRobot/letsrobot#37]

**Comment by Nocturnal42** [comment]
No, no it shouldn’t. Nothing should ever write to letsrobot.conf without the user explicitly directing it to.

**Comment by bmorrison4** [comment]
So how else should we handle whenever we make an update that requires more variables in `letsrobot.conf`? Right now there's no way to know without running the program manually.

**Comment by reltham** [comment]
Your code should handle the parameter not being in the conf file and use an appropriate default.

**Comment by Nocturnal42** [comment]
To expand upon what reltham said. You should never push changes that will break things for users without a very good reason. The only reason we are currently doing so is because this code is still essentially in testing as such it’s still somewhat acceptable. Once this code is “released” that will no longer be the case. 

If you still want to be able to backport new settings into an existing conf file, you have two options.  Adding an explicit command line option that will cause letsrobot.py to do it, or (the preferred method) create a seperate utility script people can run to do it.
