### ISSUE TITLE
Add an option for letsrobot.conf to use names for audio input / output 

### ISSUE THREAD

**Issue by skeetermcbee** [letsRobot/letsrobot#4]

**Comment by Nocturnal42** [comment]
Close. Names are not supported in either currently.

**Comment by skeetermcbee** [comment]
It'll be easy to implement from runmyrobot.

**Comment by Nocturnal42** [comment]
The code is already there. It just needs to be added in the appropriate place, to check the conf file for a name value, and if one is found, run it through getAudioDeivceByName(), and load that value into the variable for hardware num.

It's not there yet because video/audio handling was separate from the controller until recently.

**Comment by skeetermcbee** [comment]
I'm expecting that the bug where USB microphones would not have persistent card IDs in runmyrobot will come back again until it is addressed.
